title: "Qiskit Fall Fest 2025 â€” uOttawa"
description: "Workshops + hackathon. Free. Beginners welcome."
url: "https://www.uoquantum.com"     # GitHub Pages root
baseurl: ""          # Repo name, with leading slash
timezone: America/Toronto

register_url: "https://github.com/uoquantum/QFF25_Hackathon"

# "https://docs.google.com/forms/d/e/1FAIpQLSfF1xly8p6rfXzNBol6Zc0ihyqSKKBceBsTojm2oVUG0GOs_A/viewform?usp=dialog"
discord_url:  "https://discord.gg/qqgnpGsc"

markdown: kramdown
theme: null
permalink: pretty

# _config.yml
# schedule_mode: "live"   # change to "live" when the JSON/UI is ready "tba"


exclude:
  - archive/old-site/**
