title: "Qiskit Fall Fest 2025 — uOttawa"
description: "Workshops + hackathon. Free. Beginners welcome."
url: "https://www.uoquantum.com"     # GitHub Pages root
baseurl: ""          # Repo name, with leading slash
timezone: America/Toronto

register_url: "https://forms.cloud.microsoft/pages/responsepage.aspx?id=sdof1BV-_Uy1-nIA5U3ra2Da3yvAsQ9Lv33M6p7_nVpURThWSFc4QUtQRTFWU1FZVUlJVllKMDAwMi4u&route=shorturl"

# "https://docs.google.com/forms/d/e/1FAIpQLSfF1xly8p6rfXzNBol6Zc0ihyqSKKBceBsTojm2oVUG0GOs_A/viewform?usp=dialog"
discord_url:  "https://discord.gg/qqgnpGsc"

markdown: kramdown
theme: null
permalink: pretty

# _config.yml
# schedule_mode: "live"   # change to "live" when the JSON/UI is ready "tba"


# Challenges / prompts
prompts_live: false            # flip to true when the repo is public
prompts_repo: "https://github.com/uoquantum/QFF25_Hackathon"
prompts_release_time: "Nov 2, 2025 • 10:30 ET"


exclude:
  - archive/old-site/**
